### ISSUE TITLE
Test 'filters out spoofed messages' failing intermittently 

### ISSUE THREAD

**Issue by snormore** [xmtp/xmtp-js#112]
The test seems to be flakey, failing more often than not - noticed mostly in the `test:jsdom` env so far.

```
  ● Client › local docker node › filters out spoofed messages

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      264 |       })
      265 |
    > 266 |       it('filters out spoofed messages', async () => {
          |       ^
      267 |         const stream = await bob.streamConversationMessages(alice.address)
      268 |         // mallory takes over alice's client
      269 |         const malloryWallet = newWallet()
```

https://github.com/xmtp/xmtp-js/runs/6725272984?check_suite_focus=true

**Comment by snormore** [comment]
Seems to hang on this line https://github.com/xmtp/xmtp-js/blob/main/test/Client.test.ts#L277

**Comment by snormore** [comment]
@neekolas it looks like if I revert https://github.com/xmtp/xmtp-js/pull/110 then this stops happening

**Comment by snormore** [comment]
Doesn't seem to be mitigated by increasing the test timeout, so it seems that the message possibly isn't being emitted sometimes.

**Comment by snormore** [comment]
Running the test on it's own seems to work pretty consistently, at least the number of times I've tried it:
```sh
npm run test:jsdom -- -t 'Client local docker node filters out spoofed messages'
```

Running the group of client local node tests will reproduce the intermittent failures though:
```sh
npm run test:jsdom -- -t 'Client local docker node'
```

**Comment by neekolas** [comment]
My hunch is that there is a race between the filter being established and the message being received on the backend. 

Try adding a 50ms sleep before the first message is sent and see if that resolves it.

**Comment by snormore** [comment]
Just tried that and also adding 1s sleeps between pretty much everything but still seeing it

**Comment by snormore** [comment]
Ok adding a delay before the the first line (`const stream = await bob.streamConversationMessages(alice.address)`) in the test seems to mitigate it - so something about sharing/restreaming across tests

**Comment by neekolas** [comment]
That's surprising. 

Yes, the filter gets initiated in that function by sending a FilterRequest to the node.
