### ISSUE TITLE
Unsubscribe function disconnects nodes permanently

### ISSUE THREAD

**Issue by elisealix22** [xmtp/xmtp-js#139]
Using the [Stream.unsubscribeFunction](https://github.com/xmtp/xmtp-js/blob/c3d2a2f61757c3c9e6cd2c77281817b1a2385f5e/src/Stream.ts#L30) disconnects nodes from their peer and the retry loop never recovers the connection.

To reproduce:
1. Check out the `ea/all-messages` branch which [introduces a new `streamAllMessages()`](https://github.com/xmtp/xmtp-js/compare/ea/all-messages) method: https://github.com/xmtp/xmtp-js/tree/ea/all-messages.
2. Check out `ea/test-all-messages` in the react app which [integrates with the new `streamAllMessages()`](https://github.com/xmtp/example-chat-react/compare/ea/test-all-messages) method: https://github.com/xmtp/example-chat-react/tree/ea/test-all-messages
3. Run `npm run build` on the `xmtp-js` sdk to rebuild the changes.
4. Start the react app with `npm run dev` and message another wallet in another browser (it doesn't have to be a new wallet).
5. You should see the unsubscribe function is called in both browsers, but the nodes disconnect and can never recover or resubscribe.

<details>
<summary>Console output</summary>

<img width="526" alt="Screen Shot 2022-07-25 at 4 42 59 PM" src="https://user-images.githubusercontent.com/556051/180870617-9df1c831-bad2-41e9-adc4-1b1188ed9153.png">

</details>

**Comment by neekolas** [comment]
I think I found the issue. https://app.datadoghq.com/logs?query=service%3Anode-0&cols=host%2Cservice&event=AQAAAYI2n5WVi7PH8wAAAABBWUkybjVYdUFBRFBDaW9YZm5XY3hRQUI&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1658773601882&to_ts=1658774042353&live=false

I see a panic in the logs of the node at a time that coincides with one of our alerts. It's just logged at an INFO level. This must be causing the node to restart.

**Comment by mkobetic** [comment]
Hm if I view the context of that log line I get this
![Screen Shot 2022-07-25 at 16 57 58](https://user-images.githubusercontent.com/871693/180873442-4ea8ea48-ccf2-4c8d-a6ab-5025f683e661.png)

**Comment by elisealix22** [comment]
Confirmed https://github.com/xmtp/go-waku/pull/29 fixes the disconnect. Closing this out!
