### ISSUE TITLE
Paginated message retrieval

### ISSUE THREAD

**Issue by saulmc** [xmtp/xmtp-js#168]
### Context

Currently, `xmtp-js` does not expose a way to paginate a user's messages when retrieving them from the network. Pagination is available at the network level and is already used to assemble the `conversation.messages()` result. However, this result is currently only returned after the final page is loaded.

### Problem

When a user has hundreds of messages, load time appears slower because all messages in a conversation must all be retrieved from the network before any of them can be displayed.

### Goal

Provide an interface for retrieving a user's messages page-by-page, so that recent messages can be displayed sooner while older messages are still being retrieved.

**Comment by neekolas** [comment]
I'm gonna sneak this one into this sprint some time when I am blocked on something else. It feels very high ROI, given how simple it is.
