### ISSUE TITLE
Remove node storage used for test

### ISSUE THREAD

**Issue by antho1404** [xmtp/xmtp-js#189]
A `./scratch` directory is created even when the `LocalStorageStore` is not used.

https://github.com/xmtp/xmtp-js/blob/a7263d74a290f72b4faa0057a27d8463728272f6/src/store/LocalStorageStore.ts#L3

This is fine for development mode and/or tests but creates an issue for any SSR application running on a read-only environment like vercel. 

We should be able to initialize a client even in an SSR environment without any error.

Here is the error from a deployment on Vercel
<img width="1245" alt="Screen Shot 2022-10-14 at 11 35 20" src="https://user-images.githubusercontent.com/1783126/195763352-424d67bc-0dfc-4c31-b70a-f25fb1c4fa78.png">

**Comment by neekolas** [comment]
This is removed
