### ISSUE TITLE
Group conversations

### ISSUE THREAD

**Issue by mkobetic** [xmtp/xmtp-js#194]
v7.0.0 can be naturally extended to support group conversations (i.e. conversations with more than 2 participants). There isn't any technical reason why Alice couldn't send an invitation to the same conversation topic to both Bob and Charlie, and for all 3 of them to send messages to it. This simple approach comes with some limitations however:

1. There is no way to remove participants once they receive an invitation
2. There is no way for a participant to know who are all the other participants in the conversation, they can only observe who sent a message in the conversation
3. There is no way to prevent a participant from sending an invitation to others without the rest of the participants knowing
4. ... more? ...

Is any of these limitations such that we wouldn't want to release this with it?
If there are show stoppers, what would be an adequate resolution for each?

**Comment by jazzz** [comment]
> ... more? ...

Access controls, Conversation Naming/Meta data , 

> Are any of these limitations such that we wouldn't want to release this with it?

1+2+3 collectively seem  like  significant friction. Given group chat comes with a significant user expectation I imagine we'd want to move slower on this. ( to avoid having to put an asterisk on, "we have *groupchat" ) 

> If there are show stoppers, what would be an adequate resolution for each?
 
 I think the future of group chat in XMTP looks quite clear, and would address all of the items above 
 
 TreeKEM/ART -> Provable Membership, Strong encryption, ratcheting
 Topic Rotation -> Privacy with Dynamic Membership, removal
 SecureTopics -> Access Controls
 ConversationMetaDataMessages -> Rich UX

**Comment by jazzz** [comment]
I would also suggest that we break down groupchat into the 3 usecases. They come with their own UX problems and it would help ensure that everyone is talking about the same thing and not relying on assumptions

- Announcements
- DM-Groups ( <=50 users )
- Channels ( > 50 users )

**Comment by mkobetic** [comment]
Some very good points there @jazzz. I think we're coming at this from the opposite POV. You have some notion of what features should a proper solution for the various group chat use-cases have. I was coming from the other end, simply observing that v7.0.0 somewhat artificially restricts the user from sending invites to multiple parties. My mental exercise was about is it worth removing the restriction and see whether it would be useful for anything. It may not be sufficient for the use case you have in mind, but maybe it would be good enough for others. Especially since we can remove the restriction in a day compared to some unclear time frame that would be required to implement what you listed above.

**Comment by saulmc** [comment]
BIG MOMENTUM ENERGY!

I agree with @jazzz we should disambiguate group DMs, channels, and announcements as distinct use cases with their own requirements. If any one of these use cases has no show stoppers, then we should strongly consider supporting it even if a more ideal solution exists in the future.

> 1. There is no way to remove participants once they receive an invitation

Group DMs:  Not a show-stopper. Telegram does not allow this. Users can create a new group if they need to remove someone.
Channels: Show-stopper.
Announcements: Show-stopper. 

> 2. There is no way for a participant to know who are all the other participants in the conversation.

Group DMs: Show-stopper. <50 is a private environment. I wonder if background messages could help with this? e.g. Bob sends a "ping" when accepting an invite, clients fetch all the "pings" to know who is in the group.
Channels: Not a show-stopper.  >50 is a semi-public environment.
Announcements: Not a show-stopper; in fact, senders will typically prefer to keep their distribution list membership private.

> 3. There is no way to prevent a participant from sending an invitation to others without the rest of the participants knowing

Group DMs: Show-stopper (unless some background message solution exists for announcing new arrivals).
Channels: Not a show-stopper, but we'd have to message the limitation / frame the use case narrowly as "open/public" channels.
Announcements: Not a show-stopper, but we'd have to message the limitation / frame the use case narrowly as "open/public" distribnution lists.

**Comment by rygine** [comment]
group conversations coming soon

see: https://github.com/orgs/xmtp/projects/11
