### ISSUE TITLE
ENS domain capitalization error when sending messages

### ISSUE THREAD

**Issue by edisonqu** [xmtp/xmtp-js#211]
When getting ENS names, even when they are verified on the XMTP chain. Etherscan gives out two different contracts, with different lowercase and uppercase.
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/63879791/200160726-67f5fc2d-19ec-4d41-930b-70291fd77fe6.png">

When putting it through XMTP, it would not recognize that it was a valid account even though it was from the same ENS domain on etherscan.

@jazzz helped us identify this issue and hopefully this can be fixed for future updates **OR** @agxmbhir and I can help you with that

**Comment by jazzz** [comment]
Hey @edisonqu thanks for posting this! I think we can make this easier for developers such as yourself who are getting started with XMTP.

Adding some context to the above post, currently it appears XMTP requires case-senstive addresses where ethereum addresses are case-insensitive. Thought addresses can optionally be [eip55 encoded  ](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) to provide a checksum.

Current Behavior:
Attempting to message a valid lowercase address leads to an error incorrectly indicating the address is 'not on the network.'

Expected behavior:
- receive an indication that the address was typed incorrectly
or
- addresses are not rejected when they are valid but of a different case 

**example test case:**
```
 const wallet = Wallet.fromMnemonic(
      'exchange crash march aspect home blind bench electric deputy language physical gentle'
    )
    const client = await Client.create(wallet)

    assert.ok(
      await client.canMessage('0xCeda31E813cD606228E71E87E94717CD3C6F3bab')
    )
    assert.ok( // Lower case fails
      await client.canMessage('0xCeda31E813cD606228E71E87E94717CD3C6F3bab'.toLowerCase())
    )

```

@edisonqu did I get that right?

**Comment by edisonqu** [comment]
That is true, I believe a simple .toLowercase() or .toUppercase() can do the job when authenticating the if the wallet is on the network or not. 

For example: 
`  /**
   * Check if @peerAddress can be messaged, specifically it checks that a PublicKeyBundle can be
   * found for the given address
   */

**// standardizing the case for the string can make sure that all addresses can be passed through without worrying about capitalization of letters in the address**
  public async canMessage(peerAddress: string): Promise<boolean> {
    const keyBundle = await this.getUserContact(peerAddress**.toLowerCase()**)
    return keyBundle !== undefined
  }

  static async canMessage(
    peerAddress: string,
    opts?: Partial<NetworkOptions>
  ): Promise<boolean> {
    const apiUrl = opts?.apiUrl || ApiUrls[opts?.env || 'dev']
    const keyBundle = await getUserContactFromNetwork(
      new ApiClient(apiUrl, { appVersion: opts?.appVersion }),
      peerAddress**.toLowerCase()**
    )
    return keyBundle !== undefined
  }`

Please let me know if this works or if it doesn't, genuinely curious about the solution.

**Comment by saulmc** [comment]
Hey @edisonqu thank you for #220 ! Totally agree this can be made easier.

Some context on this issue and options were discussed in #172 . What do you think of the proposal of using https://docs.ethers.io/v5/api/utils/address/#utils-getAddress to standardize on the checksum format?

**Comment by edisonqu** [comment]
Hi @saulmc, thank you for addressing the pull request! I appreciate the team looking into this. 

It works perfectly fine, good way to standardize. Thanks for letting me know!

I tested it and it works wonderfully. 

`const ethers = require("ethers")

console.log("0xCeda31E813cD606228E71E87E94717CD3C6F3bab".toLowerCase())` // 0xceda31e813cd606228e71e87e94717cd3c6f3bab

console.log(ethers.utils.getAddress("0xCeda31E813cD606228E71E87E94717CD3C6F3bab".toLowerCase())) // 0xCeda31E813cD606228E71E87E94717CD3C6F3bab
console.log(ethers.utils.getAddress("0xCeda31E813cD606228E71E87E94717CD3C6F3bab")) // 0xCeda31E813cD606228E71E87E94717CD3C6F3bab

console.log("0xCeda31E813cD606228E71E87E94717CD3C6F3bab".toLowerCase()) // 0xceda31e813cd606228e71e87e94717cd3c6f3bab `

For @jazzz 's code: 

` const wallet = Wallet.fromMnemonic(
      'exchange crash march aspect home blind bench electric deputy language physical gentle'
    )
    const client = await Client.create(wallet)

    assert.ok(
      await client.canMessage(ethers.utils.getAddress('0xCeda31E813cD606228E71E87E94717CD3C6F3bab'))
    )
    assert.ok( // Lower case no longer fails 
      await client.canMessage(ethers.utils.getAddress('0xCeda31E813cD606228E71E87E94717CD3C6F3bab'.toLowerCase())))
`

Integrating the [ethers.utils.getAddress 
](https://docs.ethers.io/v5/api/utils/address/#utils-getAddress) with canMessage is the most optimal move here. Let me know if I am able to help anywhere :)
