### ISSUE TITLE
Requesting that message ID be returned when sending a message.

### ISSUE THREAD

**Issue by cucupac** [xmtp/xmtp-js#212]
Example:

Instead of:
```
await conversation.send('gm');
const messages = await conversation.messages();
const id = messages[messages.length - 1].id;
```

The following would be nice:
```
const id = await conversation.send('gm');
```

Seems like a useful thing to return, especially for use cases that need to store a message id as a foreign key for arbitrary objects.

**Comment by elisealix22** [comment]
Thanks for opening this for discussion @cucupac ! I believe you should be able to grab the `id` from [Conversation#send](https://xmtp.org/docs/client-sdk/javascript/reference/classes/Conversation#send) as we currently return the message! It would look something like:

```js
const messageId = await conversation.send('gm')?.id
```

Lmk if you're still running into trouble!

**Comment by nplasterer** [comment]
Please feel free to reopen this if you're still having issues.
