### ISSUE TITLE
conversation.streamMessages() not working in React-native

### ISSUE THREAD

**Issue by HassenMabrouki** [xmtp/xmtp-js#223]
# Context 
Attempting to use xmtp-js in React Native, I successfully integrate the SDK, I can send messages, and also get the messages list works fine.
# Problem
Listen for new messages in a conversation it's not working
```
for await (const message of await conversation.streamMessages()) {
  if (message.senderAddress === xmtp.address) {
    // This message was sent from me
    continue
  }
  console.log(`New message from ${message.senderAddress}: ${message.content}`)
}
````
# Screenshot
![Screen Shot 2022-11-16 at 12 11 51 PM](https://user-images.githubusercontent.com/95028333/202165574-f8184c9f-47d0-44eb-8c5a-837e6bdfbf7d.png)
<img width="568" alt="Screen Shot 2022-11-16 at 12 14 23 PM" src="https://user-images.githubusercontent.com/95028333/202166029-c57d9562-0943-4887-9920-099cfeb9290c.png">
# Expectation
As I followed the documentation, the expected result whenever I send a message from user A to user B, the message should be displayed for user B, but it is not the case for me.

**Comment by shipunyc** [comment]
Any updates on this issue?

Any quick fix?

**Comment by elisealix22** [comment]
I'm switching to this one now. Will report back early next week with my findings!

**Comment by elisealix22** [comment]
Just want to pop in and say this is still under investigation. I did find one issue in testing `messagesPaginated` which uses an `AsyncGenerator` under the hood. In that case, `Promise.settleAll()` was undefined though so it seems to be a separate issue. https://github.com/facebook/hermes/issues/766

Will continue to report progress as we dig in.

**Comment by elisealix22** [comment]
@HassenMabrouki @shipunyc I have a streaming demo working over in the example repo! You can find more information in the PR description, but let me know if you run into any trouble with this approach.

https://github.com/xmtp/example-chat-react-native/pull/8

**Comment by nplasterer** [comment]
Closing this out because of inactivity. Please feel free to reopen if you're still having issues.
