### ISSUE TITLE
GRPC errors are not being surfaced

### ISSUE THREAD

**Issue by mkobetic** [xmtp/xmtp-js#226]
I've confirmed that if we get a GRPC error in response to a publish request to the messaging API, e.g.:

> 2022-11-18 14:41:27 2022-11-18T19:41:27.645Z    ERROR   xmtpd.api       api request     {"node": "16Uiu2HAmNCxLZCkXNbpVPBpSSnHj9iq4HZQj7fxRzw2kj1kKSHHA", "service": "xmtp.message_api.v1.MessageApi", "method": "Publish", "client": "xmtp-js", "client_version": "xmtp-js/0.0.0-development", "app": "", "app_version": "", "client_ip": "172.24.0.1", "error": "rpc error: code = PermissionDenied desc = publishing to restricted topic", "error_code": "PermissionDenied", "error_message": "publishing to restricted topic"}

The [MessageApi.Publish]() will simply return the PublishResponse which is just an emtpy object, just like with a successful publish response. I suspect this is a problem across the whole API, that the client isn't getting any exceptions thrown in response to at least the GRPC errors.

Consequently the retry code that we have is likely not functioning as we thought. Similarly token refreshing may be broken too.

I suspect the problem might be with the generated GRPC client. The fetchReq function looks like this:

```js
export function fetchReq<I, O>(path: string, init?: InitReq): Promise<O> {
  const {pathPrefix, ...req} = init || {}

  const url = pathPrefix ? `${pathPrefix}${path}` : path

  return fetch(url, req).then(r => r.json().then((body: O) => {
    if (!r.ok) { throw body; }
    return body;
  })) as Promise<O>
}
```

**Comment by neekolas** [comment]
You could verify this by just taking down your local API and running the test suite. I don't know if the problem is general, but there is a specific issue with the publish function in the SDK (we have always been ignoring errors there from when we were using LibP2P and it was fire and forget), but since the move to GRPC actual errors are possible.

**Comment by neekolas** [comment]
The r.ok flag will be false if the HTTP status code is not 2XX. https://www.tjvantoll.com/2015/09/13/fetch-and-errors/

**Comment by mkobetic** [comment]
Yeah, but I don't see anything throwing in response to the GRPC error, maybe the gateway, doesn't set the status the way we expect? In the go client in node-go we compare strictly to 200. I'll dig in some more.

**Comment by neekolas** [comment]
This is the specific line I am referring to https://github.com/xmtp/xmtp-js/blob/main/src/Client.ts#L313

**Comment by mkobetic** [comment]
Hm, on the node side I'm seeing this delivered to the http client, response status `403 Forbidden` and body
```
"{\"code\":7,\"message\":\"publishing to restricted topic\",\"details\":[]}"
```

**Comment by mkobetic** [comment]
> This is the specific line I am referring to https://github.com/xmtp/xmtp-js/blob/main/src/Client.ts#L313

Ah OK, I was looking at https://github.com/xmtp/xmtp-js/blob/main/src/store/PrivateTopicStore.ts#L37 which goes straight to the ApiClient. I debugged it down into the client code and nothing seems to be thrown. 🤷 I'm sure I can at least write some tests for this.

**Comment by mkobetic** [comment]
OK. looks like I was wrong about `rejects.toThrow` as well. It works fine if an `Error` is thrown, but not if something else is thrown. GRPC errors are throw as object `{"code": 7, "details": [], "message": "publishing to restricted topic"}`, so `toThrow` doesn't work for that. The assertions failure `Received function did not throw` was another thing that threw me off for quite a bit.

**Comment by mkobetic** [comment]
Looks like the bit from the jest docs that I quoted above is BS as well. Tests seem to be working fine without the awaits/returns as well.

**Comment by mkobetic** [comment]
For some extra confusion it seems that `toThrow` works for non Errors in the synchronous use case. This passes
```
describe('scratch', () => {
  it('blows', () => {
    expect(() => {
      throw { mud: 7 }
    }).toThrow(Object)
  })
})

```
