### ISSUE TITLE
validating token: token expired'

### ISSUE THREAD

**Issue by paschal533** [xmtp/xmtp-js#254]
Hi, I am getting this error `validating token: token expired'` while trying to use  @xmtp/xmtp-js on my Nextjs app

**Comment by Jonathansoufer** [comment]
Hey @paschal533 did you followed the [QuickStart](https://xmtp.org/docs/client-sdk/javascript/tutorials/quickstart) and/or the [Example NextJS app](https://github.com/xmtp/example-chat-react)? Could you share the snippet, log or process where you facing such issue?

**Comment by paschal533** [comment]
Hi @Jonathansoufer, I followed the quickstart. Here is the code below.

```
import { useEffect, useContext } from "react";
import { Client } from '@xmtp/xmtp-js'
import { ethers } from 'ethers'
import Web3Modal from "web3modal";

useEffect(() => {
    const getMes = async () => {
       try {
        const web3Modal = new Web3Modal();
        const connection = await web3Modal.connect();
        const provider = new ethers.providers.Web3Provider(connection);
        const signer = provider.getSigner();
        const xmtp = await Client.create(signer)

        const conversation = await xmtp.conversations.newConversation(
          '0x00024FA2CBaF665aFaF272712261d600ef8AC1c4'
        )
    
        const messages = await conversation.messages()
        await conversation.send('gm')
    
        for await (const message of await conversation.streamMessages()) {
          console.log(`[${message.senderAddress}]: ${message.content}`)
        }
       }catch(error) {
        console.log(error)
       }
    }

     getMes();
  }, []);
```

When I run the code, it will pop up my metamask and ask me to sign two transactions... after that, it will console out this error.

```
{code: 16, message: 'validating token: token expired', details: Array(0)}

````

**Comment by Jonathansoufer** [comment]
Hey @paschal533 , thank you for sharing your code. I tried it on a fresh Next.JS project (see below) and worked perfectly connecting to Goerli network. So, from the snippet itself, seems to be all good. Are you working in an OS that you could share and allow us to debug together?

![Screenshot 2023-01-12 at 2 03 41 PM](https://user-images.githubusercontent.com/44679989/212087457-7487beae-da94-4240-bb4e-2ec10a48fba2.png)

**Comment by nplasterer** [comment]
Closing this out because of inactivity. Please feel free to reopen if you are still having issues.
