### ISSUE TITLE
Update xmtp-js code to enable generated TypeDocs to reflect true offerings of the SDK

### ISSUE THREAD

**Issue by jhaaaa** [xmtp/xmtp-js#258]
The TypeDocs being generated for xmtp-js (and published here https://xmtp.org/docs/client-sdk/javascript/reference/classes/Client) do not include all classes and interfaces.

We need some engineering time to do some work on the codebase to ensure that TypeDocs for all key classes and interfaces are being generated from the code.

We can then publish the updated docs to xmtp.org.

**Comment by neekolas** [comment]
Will go out in v8
