### ISSUE TITLE
Bug: messages are being delivered out of sequence 

### ISSUE THREAD

**Issue by ImShivraj** [xmtp/xmtp-js#289]
### Describe the bug

Basically the messages render on the frontend in a different sequence from both the senders and receivers side. This happens when we send multiple messages in a few secs but it also happens sometimes even if we send messages with an interval of time.  Its behavior is unpredictable.

We have tested this on Konnektr, Lenster, Orb, Lensport, Buttrfly, Converse and Pinsta. But the sequence comes in the correct way only in Converse app, rest all the apps have this bug.

The wrong sequence in lenster/konnektr/pinsta/orb/lensport/buttrfly [image1, image2]
![image](https://user-images.githubusercontent.com/91371092/221959667-649b7925-ddcf-47fb-a34e-9b12c39788f2.png)
![image](https://user-images.githubusercontent.com/91371092/221960110-4f4d6172-a93b-4070-bb49-597578480883.png)

### Expected behavior

The correct sequence is only shown in Converse app

![image](https://user-images.githubusercontent.com/91371092/221961717-23441196-6d25-4e42-92e5-67b54957fee8.png)
![image](https://user-images.githubusercontent.com/91371092/221961749-2d1d2a94-9b3d-4a45-b648-c26eb96be93f.png)

### Steps to reproduce the bug

Not really sure what is causing this.

Maybe it is working like it is supposed to just on the XMTP clients using React Native like Converse. Rest all the apps on the Web and Flutter are giving unordered messages. But it also doesn't work on buttrfly which is on react native i suppose. 

Its making the UX worse, would be great if it is fixed asap.

**Comment by neekolas** [comment]
Thanks for reporting this.

Few questions:
1. In your testing, are the apps open when the messages are coming in?
2. What happens when you close the apps and reload. Is the ordering correct on second load?

**Comment by ImShivraj** [comment]
1. We tried both ways. First by keeping the apps open. Second, Just Konnektr open. In both the cases, the order of messages were jumbled except converse.

2. Even if we reload nothing changes, the ordering is permanent.

**Comment by neekolas** [comment]
I'm struggling to reproduce this issue just by using the apps. Were you sending the messages in an automated way, or just through the UI?

**Comment by yash-luna** [comment]
@ImShivraj following up so we can get more info to be able to repro this issue

**Comment by ImShivraj** [comment]
As I had mentioned earlier, this issue is unpredictable and I have myself also tried reproducing it earlier with some lens accs but couldn't. Tested this with 4 lens acc, but only with 1 acc (@imkunal13.lens) it was happening (currently) . I don't understand why only a few accounts are triggering this. And it is persistent with these accounts. Earlier when i tried with @1_cryptoman it was the same but now suddenly this issue doesn't come up https://github.com/xmtp/xmtp-js/issues/289#issue-1603725306

Below are some recent trials with @imkunal13z on Konnektr & lenster where the sequence sometimes goes wrong. We gave the messages numbers to understand the real sequence :

![image](https://user-images.githubusercontent.com/91371092/228740048-79cd130f-7bf7-490f-b746-b080e17ddc6a.png)

![image](https://user-images.githubusercontent.com/91371092/228740577-2381f65a-8367-4dc9-9688-b88c54e47cf6.png)

**Comment by ImShivraj** [comment]
Tried it again with @1_cryptoman.lens and the issue showed up this time. Its really unpredictable we both used lenster & converse UI

![image](https://user-images.githubusercontent.com/91371092/228779724-be30c7a7-bb29-41b0-84bf-34801908ca21.png)

![image](https://user-images.githubusercontent.com/91371092/228780117-36b82d06-ec72-404f-893f-557d3d6b4079.png)

But this time even Converse didn't render the sequence correctly unlike https://github.com/xmtp/xmtp-js/issues/289#issue-1603725306
