### ISSUE TITLE
Bug: React production build fails

### ISSUE THREAD

**Issue by krivochenko** [xmtp/xmtp-js#309]
### Describe the bug

Currently xmtp-js has  "@noble/secp256k1": "^1.5.2" in dependencies. In process of transpiling this package there is a known issue. This issue the same as [described](https://github.com/paulmillr/noble-ed25519/issues/23). This is another package of the same owner.

Commonly used workaround by redefine browserList to late versions of browsders reduces cover of supported browsers to 30%. 

In late releases owner fixed this code. So, maybe we could use it?
 

### Expected behavior

XMTP does not fail on React production build.

### Steps to reproduce the bug

1. Define browserList
  ```  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
  ```
2. npm run build
3. server -s build

**Comment by jhaaaa** [comment]
Thank you for taking the time to file this bug report @krivochenko! I'm assigning this to a developer for further investigation.

**Comment by jhaaaa** [comment]
@neekolas Might this be something we want to include in v8? Also, I'm not sure of the severity level - might you be able to help with that, please and thank you!

cc: @rygine

**Comment by neekolas** [comment]
So, to summarize the issue:

One of our dependencies uses BigInts. They are a standard feature in newer browsers. The particular way the library uses BigInt does not work with polyfills of BigInt.

Some client applications are using a bundler/transpiler that is polyfilling BigInt to support older browsers, but breaking the dependency along the way.

One possible solution is for us to recommend that developers using `xmtp-js` define a browserlist in their own app's package.json to tell their misbehaving bundler to target only new enough browsers that the polyfill is not needed. I'd be fine with that solution, and it does seem like we can do more to communicate that `xmtp-js` is not compatible with BigInt polyfills.
