### ISSUE TITLE
Implement RAPID to dedupe conversations in JS

### ISSUE THREAD

**Issue by yash-luna** [xmtp/xmtp-js#316]
RAPID: https://www.notion.so/xmtplabs/RAPID-Dedupe-conversations-via-Determinism-18735a19ed1140fcbf95c2ea801c5422?pvs=4

**Comment by rygine** [comment]
Delivered with https://github.com/xmtp/xmtp-js/pull/326 and https://github.com/xmtp/xmtp-js/pull/383
