### ISSUE TITLE
Tracking: Technical Proof of XMTP v3 Alpha (AKA Project Mudpup)

### ISSUE THREAD

**Issue by m-005** [xmtp/xmtp-js#341]
Outline of [Project Mudpup](https://www.notion.so/xmtplabs/Project-MudPup-5ecfead9a7f049f2bf988e1b682492e8?pvs=4). The main goal was to test voodoo and learn about any complications.

**Comment by michaelx11** [comment]
For future tracking/reference:

libxmtp PRs:
https://github.com/xmtp/libxmtp/pull/30
https://github.com/xmtp/libxmtp/pull/31
https://github.com/xmtp/libxmtp/pull/32
https://github.com/xmtp/libxmtp/pull/33
https://github.com/xmtp/libxmtp/pull/34
https://github.com/xmtp/libxmtp/pull/35
https://github.com/xmtp/libxmtp/pull/36
https://github.com/xmtp/libxmtp/pull/37
https://github.com/xmtp/libxmtp/pull/38
https://github.com/xmtp/libxmtp/pull/39
https://github.com/xmtp/libxmtp/pull/40
https://github.com/xmtp/libxmtp/pull/41
https://github.com/xmtp/libxmtp/pull/42
https://github.com/xmtp/libxmtp/pull/43
https://github.com/xmtp/libxmtp/pull/44
https://github.com/xmtp/libxmtp/pull/45
https://github.com/xmtp/libxmtp/pull/46
https://github.com/xmtp/libxmtp/pull/47

xmtp-js
https://github.com/xmtp/xmtp-js/pull/322
https://github.com/xmtp/xmtp-js/pull/323
https://github.com/xmtp/xmtp-js/pull/325
https://github.com/xmtp/xmtp-js/pull/329
https://github.com/xmtp/xmtp-js/pull/332
https://github.com/xmtp/xmtp-js/pull/333

**Comment by michaelx11** [comment]
Demo branch: https://github.com/xmtp/cli-starter/tree/michaelx_voodoo_demo

All of those together should comprise the MudPup effort - along with associated Notion docs etc.
