### ISSUE TITLE
Networking framework for publish/query

### ISSUE THREAD

**Issue by m-005** [xmtp/xmtp-js#349]
Approaches:
- Hook up vodozemac crate with xmtp-networking crate in main. Write simple publish/query test from vodezemac using xmtp-networking.
- Callback-based?

**Comment by michaelx11** [comment]
Going to start by doing this in Rust land.

**Comment by michaelx11** [comment]
I'm going to release and pop this task back into the open pool.

**Comment by jazzz** [comment]
I'm happy to stay out of this for now. All yours. If there are components that can be paralleled then happy to jump back in
