### ISSUE TITLE
Deprecate Conversation ID JS

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-js#415]
Remove support for setting conversationId field for new conversations

**Comment by mkobetic** [comment]
Are we sure about this? The philosophical reason for convoIDs was that conversations were meant to be just that, transient communications, not permanent channels between identities. I probably missed a lot of what went on in the meantime, but my understanding was that we introduced deterministic convoIDs to deal with the duplicate convo problem, but does that mean that we have to do away with separating conversations altogether? Also a pragmatic reason for convoIDs was handling Lens profiles, how do we handle those without convoIDs?

**Comment by nplasterer** [comment]
Yep you're totally right. I was confused by some of the information floating around and this is actually just a docs change to let people know we no longer encourage setting it in most cases.
