### ISSUE TITLE
Add Support for Viem Signer

### ISSUE THREAD

**Issue by daria-github** [xmtp/xmtp-js#416]
### Is your feature request related to a problem?

Currently, `Client.create` needs to take a Signer from the ethers lib, which Wagmi is no longer using in recent versions, preventing us from migrating to later versions of Wagmi. 

### Describe the solution to the problem

Allow support for both the Viem Signer equivalent and ethers.

### Describe the uses cases for the feature

This will allow us to bump our Wagmi version to the latest.

**Comment by mkobetic** [comment]
I haven't looked at any details here, but we probably need a lot less than the full ethers.Signer. It might be worth just defining our own interface that would be a tiny subset of Signer.

**Comment by fabriguespe** [comment]
One developer has created this solution
_I used xmtp/xmtp-js and created function for that takes the viem wallet generated by wagmi 2 and mapped it to a mock function that would be capital with ethers wallet_
