### ISSUE TITLE
Bug: WebAssembly Module Parse Failed in Webpack Configuration

### ISSUE THREAD

**Issue by fabriguespe** [xmtp/xmtp-js#484]
### Describe the bug

After updating to XMTP v11.3.0 the application throws an error. The error message suggests that the WebAssembly module is not enabled in the Webpack configuration.
<img width="830" alt="CleanShot 2023-11-01 at 13 56 03@2x" src="https://github.com/xmtp/xmtp-js/assets/1447073/8652d3a4-da06-4d36-93a1-d4d6b1e32b69">

### Steps to reproduce the bug

- Installing or updating to XMTP v11.3.0

**Comment by fabriguespe** [comment]
The error is due to WebAssembly not being enabled in the webpack configuration. Since webpack 5, WebAssembly is not enabled by default and is flagged as an experimental feature.

You can enable WebAssembly in your webpack configuration by adding the experiments field. Here's how you can do it:

// webpack.config.js
```jsx
module.exports = {
  //...
  experiments: {
    asyncWebAssembly: true, // for async modules
    // or
    syncWebAssembly: true, // like webpack 4, but it's deprecated
  },
  //...
};
```jsx

Also, for files that transpile to WebAssembly, you need to set the module type in the module.rules section of the config. Here's an example:

```jsx
// webpack.config.js
module.exports = {
  //...
  module: {
    rules: [
      {
        test: /\.wasm$/,
        type: "webassembly/async", // for async modules
        // or
        // type: "webassembly/sync", // like webpack 4, but it's deprecated
      },
      // other rules...
    ],
  },
  //...
};
```

**Comment by fabriguespe** [comment]
The error is due to WebAssembly not being enabled in the webpack configuration. Since webpack 5, WebAssembly is not enabled by default and is flagged as an experimental feature.

You can enable WebAssembly in your webpack configuration by adding the experiments field. Here's how you can do it:

// webpack.config.js
```jsx
module.exports = {
  //...
  experiments: {
    asyncWebAssembly: true, // for async modules
    // or
    syncWebAssembly: true, // like webpack 4, but it's deprecated
  },
  //...
};
```

Also, for files that transpile to WebAssembly, you need to set the module type in the module.rules section of the config. Here's an example:

```jsx
// webpack.config.js
module.exports = {
  //...
  module: {
    rules: [
      {
        test: /\.wasm$/,
        type: "webassembly/async", // for async modules
        // or
        // type: "webassembly/sync", // like webpack 4, but it's deprecated
      },
      // other rules...
    ],
  },
  //...
};
```


If you are using @craco then on the `craco.config.js`:

```jsx
module.exports = {
  webpack: {
    configure: (config) => {
      config.experiments = {
        asyncWebAssembly: true,
        layers: true,
      };

      // turn off static file serving of WASM files
      // we need to let Webpack handle WASM import
      config.module.rules
        .find((i) => "oneOf" in i)
        .oneOf.find((i) => i.type === "asset/resource")
        .exclude.push(/\.wasm$/);

      return config;
    },
  },
};

```

**Comment by neekolas** [comment]
@rygine is working on some improvements to our webpack examples

**Comment by fabriguespe** [comment]
Awesome!

I can confirm that it is not working with NextJS

I tried the solutions mentioned in this threads, without success:

https://github.com/vercel/next.js/issues/27083
https://github.com/vercel/next.js/issues/25852
https://github.com/vercel/next.js/issues/53163

**Comment by rygine** [comment]
with the latest beta (16), use the following config to ensure WASM files are loaded:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config) => {
    // tell webpack to load WASM files as an asset resource
    config.module.rules.push({
      test: /\.wasm$/,
      type: "asset/resource",
    });
    return config;
  },
};

module.exports = nextConfig;
```

**Comment by fabriguespe** [comment]
With the latest (19) there is no need to use config anymore. 

```
/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;

```

**Comment by nguyenvuhoang** [comment]
> ```js
> config.module.rules.push({
>       test: /\.wasm$/,
>       type: "asset/resource",
>     });
> ```

When we'try change config.  --> it was showed one message errror wasm.language_new_plutus_v1 is not a function

**Comment by JohnnyGoodpick** [comment]
> I tried to implement this on Nextjs in order to make beta version work but it doesnt solve the issue in my case.
> 
> I dont believe there's much to do but I'm not too familiar with this, the initial error saying to set the experimental webassembly support has disappeared, I only get this error now:
> 
> `ENOENT: no such file or directory, open 'C:\work\test\.next\server\chunks\user_preferences_bindings_wasm_bg.wasm'`
> 
> Any advice to implement this on Nextjs 14 ?
> 
> Here's our next.config.js:
> 
> ```js
> const nextConfig = {
> 	compiler: {
> 		styledComponents: { displayName: false },
> 	},
> 	webpack: (config, { isServer }) => {
> 		const experiments = config.experiments || {}
> 		config.experiments = { ...experiments, asyncWebAssembly: true, layers: true }
> 		config.module.rules.push({
> 			test: /\.wasm$/,
> 			type: "webassembly/async",
> 		})
> 		return config
> 	},
> 	reactStrictMode: true,
> 	staticPageGenerationTimeout: 100,
> }
> ```

There seems to be a regression on this between v5.0.3 (working) and 5.1.0 on @xmtp/react-sdk, 
I am getting the same error message as before when updating.

**Comment by fabriguespe** [comment]
I managed to make it work in this quickstart using this code in the Parent of the components

```jsx
import dynamic from 'next/dynamic';
const FloatingInbox = dynamic(() => import('./FloatingInbox-hooks'), { ssr: false });
```

https://github.com/fabriguespe/xmtp-quickstart-hooks-next

**Comment by rygine** [comment]
@fabriguespe i wonder if marking the component that uses WASM as client only would also solve this...

**Comment by fabriguespe** [comment]
You mean using `"use client"`? That didn't work.

**Comment by fabriguespe** [comment]
Im also experiencing this on localhost:

```
(base) fabrizioguespe@fabrizios-MacBook-Pro xmtp-quickstart-hooks-next % bun run dev                             
$ next dev
   ▲ Next.js 14.0.4
   - Local:        http://localhost:3000

 ✓ Ready in 1212ms
 ○ Compiling / ...
 ✓ Compiled / in 1209ms (2136 modules)
 ⨯ Error: ENOENT: no such file or directory, open '/Users/fabrizioguespe/DevRel/xmtp-quickstart-hooks-next/.next/server/vendor-chunks/user_preferences_bindings_wasm_bg.wasm'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at __webpack_require__ (/Users/fabrizioguespe/DevRel/xmtp-quickstart-hooks-next/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/fabrizioguespe/DevRel/xmtp-quickstart-hooks-next/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/Subscribe/index.js:9:71)
    at (ssr)/./src/app/Subscribe/index.js (/Users/fabrizioguespe/DevRel/xmtp-quickstart-hooks-next/.next/server/app/page.js:437:1)
    at __webpack_require__ (/Users/fabrizioguespe/DevRel/xmtp-quickstart-hooks-next/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/page.js:10:68)
    at (ssr)/./src/app/page.js (/Users/fabrizioguespe/DevRel/xmtp-quickstart-hooks-next/.next/server/app/page.js:448:1)
    at __webpack_require__ (/Users/fabrizioguespe/DevRel/xmtp-quickstart-hooks-next/.next/server/webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
 ○ Compiling /favicon.ico ...
 ✓ Compiled /favicon.ico in 821ms (1069 modules)
```

**Comment by rygine** [comment]
@fabriguespe is this still an open issue?

**Comment by neekolas** [comment]
Have we documented how and when to use dynamic imports to fix this issue?

**Comment by JohnnyGoodpick** [comment]
This bug was gone so far but it seems to have reappeared after I updated these:

From:
```
"@xmtp/content-type-reaction": "^1.1.7",
"@xmtp/content-type-remote-attachment": "^1.1.8",
"@xmtp/content-type-reply": "^1.1.9",
```
To:
```
"@xmtp/content-type-reaction": "^1.1.9",
"@xmtp/content-type-remote-attachment": "^1.1.9",
"@xmtp/content-type-reply": "^1.1.11"
```
I use same config (nextjs) as previously, latest versions for everything

**Comment by JohnnyGoodpick** [comment]
It seems that whenever @xmtp/user-preferences-bindings-wasm@^0.3.5 gets updated to 0.3.6 from "@xmtp/content-type-remote-attachment": "^1.1.9", or "@xmtp/content-type-reply": "^1.1.11" , the build will fail on nextjs

**Comment by wutzebaer** [comment]
My temporary "fix" for

rror: ENOENT: no such file or directory, open 'XXX\.next\server\static\wasm\9607384f0e83ab1b.wasm'

run `npm run build` in cmd shell

Wait for `✓ Collecting page data`

Hit pause

copy `.next\server\chunks\static`
to `.next\server\static`

resume console

**Comment by rozzrr** [comment]
we are having this issue, none of the workarounds seem to fix this
