### ISSUE TITLE
Bug: Module not found: Can't resolve '@xmtp/xmtp-js'

### ISSUE THREAD

**Issue by emmajane1313** [xmtp/xmtp-js#515]
### Describe the bug

This error started showing up today in my nextjs app that's using the @xmtp/react-sdk packet v^4.0.0. All deployments prevously havent caused any errors, just showed up today when running npm run build (and without changing any other packets or versions in the packge.json).

Did something update or is there a breaking change implemented?

Clearing cache, nm, package-lock, .next and rebuilding doesnt solve it. Nor does downgrading. 

I was previously only using the @xmtp/react-sdk but also downloaded the @xmtp/xmtp-js packet to see if this would result in a fix, unfortunately it hasn't.

Versions:
```
"@xmtp/react-sdk": "^4.0.0",
 "@xmtp/xmtp-js": "^11.3.3",
 "eslint": "^8",
"eslint-config-next": "13.5.4",
"postcss": "^8",
"tailwindcss": "^3",
"ts-loader": "^9.5.1",
"typescript": "^5"
"viem": "1.20.0",
"wagmi": "1.4.12",
"ethers": "^6.8.1",
"next": "13.5.4",
```

### Expected behavior

App to build when using @xmtp/react-sdk.

**Comment by rygine** [comment]
apologies for the error. a recent update did not include a path update. #516 should fix the issue.

**Comment by emmajane1313** [comment]
awesome, working again!

**Comment by emmajane1313** [comment]
awesome, working again

**Comment by emmajane1313** [comment]
@rygine I think the lastest version is exposing another error ,getting this:
```
/node_modules/@xmtp/xmtp-js/dist/index.js:7
import { keccak256 } from 'js-sha3';
```

this is for versions:
```
"@xmtp/react-sdk": "^4.0.0",
"@xmtp/xmtp-js": "^11.3.4",
```
