### ISSUE TITLE
Feature request: Expose Get Addresses by InboxId - MLS Client

### ISSUE THREAD

**Issue by alexrisch** [xmtp/xmtp-js#675]
### Is your feature request related to a problem?

In the MLS Client, it would be helpful to be able to get a list of addresses that are connected to a given inboxId as a lookup

### Describe the solution to the problem

Addresses are typically standard to make connections (like ENS)
It's helpful to have ways to connect an inboxId to an address(es) 
I think it would look something like the canMessage

**Comment by rygine** [comment]
resolved by #678
