### ISSUE TITLE
Deriving bits failed - hkdf in Electron

### ISSUE THREAD

**Issue by emilio-im** [xmtp/xmtp-js#84]
hey 👋 ,

I'm integrating xmtp in an Electron App and I'm getting this error while creating xmtp's client: `[Error: Deriving bits failed]`.

Doing some research I found that there're some issues and bugs using crytpo's hkdf method ([ref](https://github.com/electron/electron/issues/31634)). It seems they're not gonna fix that soon, so I found that the same guy that posted the issue on Electron's repo created [a library](https://github.com/panva/hkdf) that solves that issue.

Also while I was debugging the issue I found that [this](https://github.com/xmtp/xmtp-js/blob/main/src/crypto/encryption.ts#L54) was the line throwing the error, so the issue itself it's on the [hkdf method](https://github.com/xmtp/xmtp-js/blob/main/src/crypto/encryption.ts#L78-L91).

Thanks in advance and let me know if you have any question or if there's something I can do to help 😄

**Comment by rygine** [comment]
this was resolved with this commit: https://github.com/xmtp/xmtp-js/commit/e18e538df10ed828bcb92ff0965e878716d207dc
